site_name: "Apuntes de Iniciación al diseño Web © Antonio Díaz Santamaría"
site_author: Antonio Díaz Santamaría
theme:
  name: 'material'
  palette:
    primary: 'indigo'  # Color primario
    accent: 'red'      # Color de acento
  features:
    - navigation.sections  # Expansión y colapso de las secciones
    - navigation.instant   # Desplazamiento rápido
    - toc.hide             # oculta la barra lateral derecha
    - navigation.top
    - navigation.tabs
      # quita el footer por defecto
extra:
  social: []
  copyright: ""
  generator: false
extra_css:
  - 'assets/css/custom.css'  # Ruta al archivo CSS que acabamos de crear  
  - 'assets/css/stylesheets.css'
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
nav:
  - UD1: 
      - "1 Introducción a HTML": "u01/01-01.md"
      - "2 Estructura básica de un documento HTML": "u01/01-02.md"
      - "3 Etiquetas de texto en HTML": "u01/01-03.md"
      - "4 Listas en HTML": "u01/01-04.md"
      - "5 Enlaces en HTML": "u01/01-05.md"
      - "6 Imágenes en HTML": "u01/01-06.md"
      - "7 Estructura semántica en HTML": "u01/01-07.md"
      - "8 Validación y pruebas en navegadores": "u01/01-08.md"
  - UD2: 
      - "1 Formateo adicional y caracteres especiales": "u02/02-01.md"
      - "2 Vídeos y Audios": "u02/02-02.md"
      - "3 Tablas en HTML":
          - "Introducción": "u02/02-03-01.md"
          - "Atributos clásicos": "u02/02-03-02.md"
          - "Estructura semántica y accesibilidad": "u02/02-03-03.md"
          - "Tablas complejas y anidadas": "u02/02-03-04.md"
      - "4 Formularios en HTML":
          - "Introducción": "u02/02-04-01.md"
          - "Controles básicos": "u02/02-04-02.md"
          - "Controles avanzados y validación nativa": "u02/02-04-03.md"
          - "Organización de formularios largos": "u02/02-04-04.md"
          - "Buenas prácticas y resumen": "u02/02-04-05.md"
      - "5 Accesibilidad y SEO en HTML":
          - "Accesibilidad - Conceptos básicos": "u02/02-05-01.md"
          - "SEO - Conceptos básicos": "u02/02-05-02.md"
      - "6 Validación y pruebas en navegadores":
          - "Validación de HTML": "u02/02-06-01.md"
          - "Compatibilidad": "u02/02-06-02.md"
          - "Buenas prácticas finales": "u02/02-06-03.md"
      - "7 Dar formato con HTML (sin CSS)": "u02/02-07.md"

  - UD3:
      - "¿Qué es CSS?": u03/03-01.md
      - "Dónde escribir CSS": u03/03-02.md
      - "Sintaxis y selectores básicos": u03/03-03.md
      # El Box Model se introduce pronto, como base mental
      - "El modelo de caja (Box Model)": u03/03-04.md
      - "Selectores individuales": u03/03-05.md
      - "Actividad guiada": u03/03-06.md
      - "Propiedades básicos": u03/03-07.md
      - "Selectores de combinación": u03/03-08.md
      - "Actividad guiada": u03/03-09.md
      - "Propiedades estéticas": u03/03-10.md
      - "Pseudoselectores": u03/03-11.md
      - "Actividad guiada": u03/03-12.md
      # Teoría para entender conflictos de estilos
      - "Herencia y cascada": u03/03-13.md
      - "Buenas prácticas en CSS": u03/03-14.md
      - "Actividades propuestas": u03/03-15.md

  - UD4:
      - Estructura de una página web: u04/04-01.md
      - Flujo del documento y propiedad display:  u04/04-02.md
      - Centrado de elementos:  u04/04-03.md
      - Posicionamiento básico con CSS:  u04/04-04.md
      - Introducción a Flexbox:  u04/04-05.md
      - Flexbox:  u04/04-06.md
      - Introducción al diseño responsive:  u04/04-07.md
      - Media Queries básicas:  u04/04-08.md
      - Imágenes y texto adaptables:  u04/04-09.md
      - Proyecto práctico final:  u04/04-10.md
