site_name: "Apuntes de Iniciación al diseño Web © Antonio Díaz Santamaría"
site_author: Antonio Díaz Santamaría
theme:
  name: 'material'
  palette:
    primary: 'indigo'  # Color primario
    accent: 'red'      # Color de acento
  features:
    - navigation.sections  # Expansión y colapso de las secciones
    - navigation.instant   # Desplazamiento rápido
    - toc.hide             # oculta la barra lateral derecha
    - navigation.top
    - navigation.tabs
      # quita el footer por defecto
extra:
  social: []
  copyright: ""
extra_css:
  - 'assets/css/custom.css'  # Ruta al archivo CSS que acabamos de crear  
  - 'assets/css/stylesheets.css'
nav:
  - Índice: 'index.md'
  - UD1: 
      - "1.1 Introducción a HTML": "u01/01-01.md"
      - "1.2 Estructura básica de un documento HTML": "u01/01-02.md"
      - "1.3 Etiquetas de texto en HTML": "u01/01-03.md"
      - "1.4 Listas en HTML": "u01/01-04.md"
      - "1.5 Enlaces en HTML": "u01/01-05.md"
      - "1.6 Imágenes en HTML": "u01/01-06.md"
      - "1.7 Estructura semántica en HTML": "u01/01-07.md"
      - "1.8 Validación y pruebas en navegadores": "u01/01-08.md"
